### ISSUE TITLE
Stub

### ISSUE THREAD

**Issue by andreyleonardo** [whatthewhat/simple_segment#12]
Hey,
Nice work with this gem.

I would like to know if it's possible to stub the calls like on the official gem.
On the official gem is possible to do this:
`Segment::Analytics.new(write_key: Rails.application.secrets.segment_api_key, stub: true)`
It's the best way to avoid unnecessary segment calls on development or/and automated tests.

**Comment by whatthewhat** [comment]
Hey, thanks!

I actually did not notice the `stub` option in the official gem (or maybe I chose to ignore it at the time..). I think it makes sense to add this if only for API compatibility. A PR that adds this option will be more then welcome 😉

**Comment by andreyleonardo** [comment]
Cool! I'll fork the project and give a look on the code to see how I could help. 😄

**Comment by whatthewhat** [comment]
Closed by https://github.com/whatthewhat/simple_segment/pull/14
