### ISSUE TITLE
Change the batch endpoint to /v1/batch

### ISSUE THREAD

**Issue by whatthewhat** [whatthewhat/simple_segment#21]
See https://github.com/segmentio/analytics-ruby/issues/142

**Comment by JakubKopys** [comment]
@whatthewhat could you confirm if it is this still an issue? I would gladly work on that

**Comment by whatthewhat** [comment]
Hey @JakubKopys! As far as I can tell most official clients have switched to [batch](https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#batch) (except for analytics-ruby 🤷), I'll gladly accept a PR that changes it.

**Comment by sgallag-insta** [comment]
Hi @whatthewhat , just want to check, are you still open for PRs on this issue? I really need this functionality, so I'm planning to implement it very soon.

**Comment by whatthewhat** [comment]
Hey @sgallag-insta, yes, I'll gladly accept a PR for this!

**Comment by whatthewhat** [comment]
Closed via https://github.com/whatthewhat/simple_segment/pull/40
