### ISSUE TITLE
proxy from env support?

### ISSUE THREAD

**Issue by saks** [whatthewhat/simple_segment#25]
Hi!
We found that `simple_segment` fails to connect to Segment API if `HTTPS_PROXY` env var is provided. It looks like the issue lies in the use of `Net::HTTP.start` method which accepts explicit proxy settings but does not favour env vars. 

We've tried rewriting `SimpleSegment::Request#post` without method `start` and it seems works fine.

**Comment by whatthewhat** [comment]
Hey @saks!
I don't personally use proxies on the projects that use this gem, but [looking at the docs](https://ruby-doc.org/stdlib-2.5.0/libdoc/net/http/rdoc/Net/HTTP.html#method-c-start) it seems like `Net::HTTP.start` should be using the env variable as well 🤔 

I'm not opposed to switching from `Net::HTTP.start` to something else, as long as there's no breaking change to [http_options](https://github.com/whatthewhat/simple_segment#set-http-options) if you want to submit a PR.

btw, what ruby version are you running?

**Comment by saks** [comment]
Hey! Thanks for looking into it. You're right, it's a little change that was necessary to make `Net::HTTP.start` consider proxy settings from env vars. 
We use 2.4.9, going to upgrade soon, but I don't expect any difference in the behaviour.

I've prepared a little [PR](https://github.com/whatthewhat/simple_segment/pull/26) to address it, please have a look.
