### ISSUE TITLE
Track event send properties key with nil value

### ISSUE THREAD

**Issue by wenga86** [whatthewhat/simple_segment#27]
When a send a track event call without properties it still includes the properties key and with a null value, which according to Segments debugger is a violation.

<img width="485" alt="Screen Shot 2020-07-09 at 3 06 50 PM" src="https://user-images.githubusercontent.com/1208662/87086195-d6517680-c1f6-11ea-8bbf-44f78f1f8338.png">
<img width="316" alt="Screen Shot 2020-07-09 at 3 16 48 PM" src="https://user-images.githubusercontent.com/1208662/87086456-3e07c180-c1f7-11ea-851f-d17d38750d69.png">

Would it be possible to compact the object before sending it to Segment to avoid this?

**Comment by whatthewhat** [comment]
Hey @wenga86, thanks for reporting this! Looks like the official gem is using an empty hash in this case, we'll do the same - https://github.com/whatthewhat/simple_segment/pull/28. I'll likely merge/release the change this weekend.
