### ISSUE TITLE
BASE_URL is hardwired

### ISSUE THREAD

**Issue by mshappe** [whatthewhat/simple_segment#35]
Segment now supports two regions, allowing for EU-specific data collection, but SimpleSegment currently hard-wires the US Segement's `api.segment.io` URL.

(For comparison, `analytics-ruby` now supports a `host` parameter on client initialization).

**Comment by davidmhleung** [comment]
@mshappe - https://github.com/whatthewhat/simple_segment/pull/36/files addresses this issue.

**Comment by whatthewhat** [comment]
Hey everyone, thanks for bringing this up, definitely something that makes sense to add 👍 Left a comment in the PR.

**Comment by whatthewhat** [comment]
Addressed in https://github.com/whatthewhat/simple_segment/pull/37
